# Use lightweight Node
FROM node:24-alpine

# Set working directory
WORKDIR /app

# Copy only package files first for caching
COPY package*.json ./

# Install dependencies (including devDependencies)
RUN npm install

# Expose your backend port
EXPOSE 3000

# Use the dev command defined in package.json
CMD ["npm", "run", "dev"]